package llm

import (
	"encoding/json"
	"fmt"
)

// ChatCompletionRequest represents a request structure for chat completion API.
type ChatCompletionRequest struct {
	Messages       []*ChatCompletionMessage `json:"messages,omitnil,omitempty" name:"messages"`
	*InvokeOptions                          // base request options
}

// ChatCompletionMessage ...
type ChatCompletionMessage struct {
	Role    string `json:"role"`
	Content string `json:"content,omitempty"`
	// 多种类型内容（支持图片和文本）
	MultipartContent []*MultipartContent `json:"contents,omitnil,omitempty" name:"contents"`
	// For Role=assistant prompts this may be set to the tool calls generated by the model, such as function calls.
	ToolCalls []*ToolCall `json:"tool_calls,omitempty"`
	// For Role=tool prompts this should be set to the ID given in the assistant's prior request to call a tool.
	ToolCallID string `json:"tool_call_id,omitempty"`
}

// 序列化 ChatCompletionMessage
func (c *ChatCompletionMessage) MarshalJSON() ([]byte, error) {
	var xxx struct {
		Role       string      `json:"role"`
		Content    any         `json:"content,omitempty"`
		ToolCalls  []*ToolCall `json:"tool_calls,omitempty"`
		ToolCallID string      `json:"tool_call_id,omitempty"`
	}
	xxx.Role = c.Role
	if c.Content != "" {
		xxx.Content = c.Content
	}
	if len(c.MultipartContent) > 0 {
		parts := []map[string]any{}
		for _, part := range c.MultipartContent {
			fmt.Println("part.Type: ", part.Type)
			fmt.Println("part.Data: ", part.Data)
			if part.Type == "text" {
				parts = append(parts, map[string]any{
					"type": part.Type,
					"text": part.Data,
				})
			} else if part.Type == "image_url" {
				parts = append(parts, map[string]any{
					"type":      part.Type,
					"image_url": part.Data,
				})
			} else {
				parts = append(parts, map[string]any{
					"type":    part.Type,
					part.Type: part.Data,
				})
			}
		}
		xxx.Content = parts
	}
	if len(c.ToolCalls) > 0 {
		xxx.ToolCalls = c.ToolCalls
	}
	if c.ToolCallID != "" {
		xxx.ToolCallID = c.ToolCallID
	}

	return json.Marshal(&xxx)
}

// Content ...
type ChatContent struct {
	// 内容类型
	// 注意：
	// 当前只支持传入单张图片，传入多张图片时，以第一个图片为准。
	// 注意：此字段可能返回 null，表示取不到有效值。
	Type string `json:"type,omitnil,omitempty" name:"type"`

	// 当 Type 为 text 时使用，表示具体的文本内容
	// 注意：此字段可能返回 null，表示取不到有效值。
	Text string `json:"text,omitnil,omitempty" name:"text"`

	// 图片的url，当 Type 为 image_url 时使用，表示具体的图片内容
	// 如"https://example.com/1.png" 或 图片的base64（注意 "data:image/jpeg;base64," 为必要部分）："data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAA......"
	// 注意：此字段可能返回 null，表示取不到有效值。
	ImageURL *ChatImageURL `json:"image_url,omitnil,omitempty" name:"image_url"`
}

// ChatImageURL ...
type ChatImageURL struct {
	// 图片的 Url（以 http:// 或 https:// 开头）
	// 注意：此字段可能返回 null，表示取不到有效值。
	URL string `json:"url,omitnil,omitempty" name:"url"`
}
